### ISSUE TITLE
Update for koios version from v0 api to v1 api

### ISSUE THREAD

**Issue by AstroWa3l** [QuixoteSystems/koios-python#12]
The new release has breaking changes and new endpoints that will need to be added, you can view them [here](https://github.com/cardano-community/koios-artifacts/releases/tag/v1.1.0rc) in their GitHub repo. 

I wanted to just make a todo list of what needs to be completed to upgrade the koios-python library.

### Deprecations
- [x] `/tx_utxos` - No longer required as replaced by /utxo_info [#227](https://github.com/cardano-community/koios-artifacts/pull/227)

### New endpoints added
- [x] `/pool_registrations` - List of all pool registrations initiated in the requested epoch [#239](https://github.com/cardano-community/koios-artifacts/pull/239)

- [x] `/pool_retirements` - List of all pool retirements initiated in the requested epoch [#239](https://github.com/cardano-community/koios-artifacts/pull/239)

- [x] `/treasury_withdrawals` - List of withdrawals made from treasury [#239](https://github.com/cardano-community/koios-artifacts/pull/239)

- [x] `/reserve_withdrawals` - List of withdrawals made from reserves (MIRs) [#239](https://github.com/cardano-community/koios-artifacts/pull/239)

- [x] `/account_txs` - Transactions associated with a given stake address [#239](https://github.com/cardano-community/koios-artifacts/pull/239)

- [x] `/address_utxos` - Get UTxO details for requested addresses [#239](https://github.com/cardano-community/koios-artifacts/pull/239)

- [x] `/asset_utxos` - Get UTxO details for requested assets [#239](https://github.com/cardano-community/koios-artifacts/pull/239)

- [x] `/script_utxos` - Get UTxO details for requested script hashes [#239](https://github.com/cardano-community/koios-artifacts/pull/239)

- [x] `/utxo_info` - Details for requested UTxO arrays [#239](https://github.com/cardano-community/koios-artifacts/pull/239)

- [x] `/script_info` - Information about a given script FROM script hashes [#239](https://github.com/cardano-community/koios-artifacts/pull/239)

- [x] `/ogmios` - Expose [Ogmios](https://ogmios.dev/api/#operation-publish-/) [endpoints]( https://github.com/cardano-community/guild-operators/pull/1690 )

**Comment by QuixoteSystems** [comment]
Great Wael! I'm going to start to test each new endpoint and I will keep updated all the work I've done.

**Comment by AstroWa3l** [comment]
Might be nice to add compression as well by default...We also need to add a way to have Bearer tokens but I can not test them since Koios team has not yet finished that part of the project's milestone.

**Comment by AstroWa3l** [comment]
Okay, I am finished with the main updates but still need to try to add the compression by default feature and then do a lot of testing. @QuixoteSystems I have made a separate branch for this update once we have finished testing and are okay with updating the repo we can merge the branch into the main branch.
